dev.langchain4j.cdi.plugin.chat-model.class=dev.langchain4j.model.openai.OpenAiChatModel
dev.langchain4j.cdi.plugin.chat-model.config.api-key={{OPEN_API}}
dev.langchain4j.cdi.plugin.chat-model.config.model-name=gpt-5
jnosql.keyvalue.database=olympus
jnosql.document.database=machines
jnosql.oracle.nosql.host=http://localhost:8080